In [5]:
import numpy as np

# **Comparsion between numpy vs list**

Time taken by numpy array vs list

In [1]:
from time import process_time

In [3]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0015457889999996866


In [6]:
np_array = np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0015171849999999765


In [9]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
# numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
# starting a 1D array
array1 = np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [14]:
array1.shape

(4,)

In [15]:
# create 2D array
array2=np.array([[1,2,3,4],[5,6,7,8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
array2.shape

(2, 4)

In [17]:
array3 = np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
print(array3)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy array

In [18]:
# create a numpy array of zeros
array4 = np.zeros((4,6))
print(array4)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
# creating a numpy array of one's
array5=np.ones((3,4))
array5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# numpy array having articular value
array6 = np.full((3,3),6)
array6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [21]:
# creating identity matrix(same number of rows and columns)
array7 = np.eye(4)
array7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# creating a numpy array with random values
array8 = np.random.random((3,4))
array8

array([[0.55557164, 0.35253454, 0.57168237, 0.18069734],
       [0.60677791, 0.25077879, 0.80682021, 0.55842039],
       [0.07061058, 0.98828153, 0.18202429, 0.81522088]])

In [24]:
# random integer values
array9 = np.random.randint(100,1000,10)
array9

array([790, 400, 162, 628, 484, 103, 960, 602, 369, 902])

In [25]:
# array with evenly spaced values-------> specifying the number of values required
array_10 = np.linspace(10,30,5)
array_10

array([10., 15., 20., 25., 30.])

In [26]:
# array with evenly spaced values-------> specifying the step
array_11 = np.arange(10,30,5)
array_11

array([10, 15, 20, 25])

In [29]:
# convert list to numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analyzing numpy array

In [31]:
a = np.random.randint(10,90,(5,5))
print (a)

[[14 21 79 49 20]
 [61 32 24 67 16]
 [69 14 49 44 28]
 [50 47 40 18 86]
 [81 30 56 64 21]]


In [32]:
# array dimension
a.shape

(5, 5)

In [33]:
# number of dimensions in array a
a.ndim

2

In [34]:
# number of elements in array a
a.size

25

In [35]:
# checking datatypes of values in array a
a.dtype

dtype('int64')

Mathematical operations on numpy array

In [36]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [37]:
b = np.random.randint(0,10,(3,3))
c = np.random.randint(10,20,(3,3))

In [38]:
b

array([[2, 8, 7],
       [9, 9, 8],
       [3, 4, 1]])

In [39]:
c

array([[10, 16, 19],
       [14, 15, 18],
       [19, 12, 12]])

In [40]:
b+c

array([[12, 24, 26],
       [23, 24, 26],
       [22, 16, 13]])

In [41]:
b-c

array([[ -8,  -8, -12],
       [ -5,  -6, -10],
       [-16,  -8, -11]])

In [42]:
b*c

array([[ 20, 128, 133],
       [126, 135, 144],
       [ 57,  48,  12]])

In [43]:
b/c

array([[0.2       , 0.5       , 0.36842105],
       [0.64285714, 0.6       , 0.44444444],
       [0.15789474, 0.33333333, 0.08333333]])

In [45]:
d = np.random.randint(0,10,(3,3))
g = np.random.randint(10,20,(3,3))

In [46]:
print(d)
print(g)

[[1 4 9]
 [6 4 1]
 [5 6 9]]
[[16 17 15]
 [16 12 11]
 [14 15 10]]


In [47]:
print(np.add(d,g))
print(np.subtract(d,g))
print(np.multiply(d,g))
print(np.divide(d,g))

[[17 21 24]
 [22 16 12]
 [19 21 19]]
[[-15 -13  -6]
 [-10  -8 -10]
 [ -9  -9  -1]]
[[ 16  68 135]
 [ 96  48  11]
 [ 70  90  90]]
[[0.0625     0.23529412 0.6       ]
 [0.375      0.33333333 0.09090909]
 [0.35714286 0.4        0.9       ]]


In [48]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 4 1]
 [4 6 2]]
(2, 3)


In [49]:
# transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[9 4]
 [4 6]
 [1 2]]
(3, 2)


In [50]:
tans2 = array.T
print(tans2)
print(tans2.shape)

[[9 4]
 [4 6]
 [1 2]]
(3, 2)


In [51]:
# reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 4 4]
 [2 4 7]]
(2, 3)


In [52]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 4]
 [4 2]
 [4 7]]
(3, 2)
